version: '3.8'
services: 
    postgres:
        image: postgres
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=hypertube
        expose:
            - "5432"
        ports: 
            - "5432:5432"
        volumes: 
            - "./database/db/data:/var/lib/postgresql/data"
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/usr/app'
            - '/usr/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    api:
        container_name: api
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - './api:/usr/app'
            - '/usr/app/node_modules'
        ports:
            - 5000:5000
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - postgres